### PR TITLE
Some minor updates to the script

### PR DESCRIPTION
**Pull request by ezaton**
I have modified the script in the following manner:

- Renamed the file from a name containing spaces to underscores instead (for ease of use by many less-knowledgeable users)
- Some linting and syntax cleaning
- Obtaining from /etc/crypttab the name of devices and iterating over it - allows for using the TPM2 single key stored for all encrypted disks, and also - not hard-coded on /dev/sda3 anymore.

### CODE REVIEW

**Comment by kelderek** [comment]
I totally agree about the file name needing to change.  I was planning take out the spaces, too.  Also I am going to shorten it as I made the name way too long.

I have some concerns about the automatic enrolling of all drives in crypttab, though:
1) The user may not want all drives automatically unlocked at boot
2) I am not 100% confident that the naming will always be consistent e.g. sda3_crypt so you can say /dev/${disk}.  I have a setup where it pulls the name from /etc/crypttab, then uses cryptsetup status <name> to pull the device name
3) My original error message needs to be modified as well

Doing a wc -l on /etc/crypttab may be more than one even with a single drive listed if there is a comment, or even just extra empty lines, given a false warning message.  This will also be addressed in my upcoming update because it will be able to update all the relevant lines

The final command showing how to remove the LUKS key will only show the last of the disks changed.  Not a big deal as it is just guidance, but it might be confusing to the end user.  This will also be addressed in my update.

I am going to try to wrap up some of the big changes today, which also addresses all the changes in this PR.  If I can't get it finished by the end of the day, I will go ahead and accept your PR as it is still improves what I have out there now :)

**Comment by ezaton** [comment]
Assumptions: 
1. This is a default Ubuntu installation, and thus - this is how crypttab looks
2. This installation has LVM spanning over two (or more) physical disks, meaning crypttab will reflect Ubuntu's configuration.
Therefore, I think this is safe enough, and if things are weird, the script will fail.

**Comment by kelderek** [comment]
Those are reasonable enough expectations for 99% of cases, but because we are messing with low level stuff, I want to be extra cautious.  I will go ahead and merge this PR, but I should be done soon with the changes that should be safe in 99.9% of cases, and allows the user additional control over which devices are selected.

**Comment by ezaton** [comment]
Listen - the purpose of the script is to save time and reduce chances of mistake to a newcomer to Linux or a person who has set mind about encrypting the disk. I think it should be rather simple - Assume "defaults", but if not - exit, and point the person to a real guide. The guide makes sense of the layers below, so there should be no problem there. My 2 cents. I am all into helping people, but it has to be reasonable. You cannot anticipate any and every scenario out there, and attempting to do so would make the whole process complex beyond easy maintenance. Again - my opinion.

**Comment by kelderek** [comment]
I just created a v0.8.0-alpha.1 branch with my big changes.  I haven't merged it to main yet because I have only done preliminary testing so far.  I will try to get some additional testing done tomorrow, but it should be a LOT more friendly to a newcomer, and should keep people from having to edit the script itself and/or their /etc/crypttab.

If you have a chance to try it out and share your thoughts, I would love to hear it :)

**Comment by kelderek** [comment]
FYI when I was testing my v0.8.0 update, I found that on my Ubuntu test VMs (using qemu/kvm and virt-manager) it defaulted to /dev/vd* for the virtual devices (e.g. /dev/vda) but dm_crypt-0 for the name in crypttab, so in that case assuming the crypttab name is <device>_crypt would fail.  Granted, I doubt many people are trying to encrypt on a VM, but it is dangerous to assume crypttab will always use <device>_crypt, especially when it isn't too hard to have cryptsetup just tell us what the device path is

**Comment by ezaton** [comment]
I use a vm with snapshots (based on ZFS) to run the same process. In my case, because the next step is using grub-standalone, which has a bug with virtio and EFI (which almost no one encounters, so no fix for that), I am using "sata" disk controller, and my disks are /dev/sda and so on. I think that my fix will work just fine on vda devices. At the current state of the code, with a single disk - I see no reason for the script to fail.

**Comment by kelderek** [comment]
Your fix would fail adding the key to the volume:

```
for disk in `cat /etc/crypttab | awk '{print $1}' | sed 's/_.*//'`
do
    echo
    echo Adding the new key to LUKS.  You will need to enter the current passphrase used to unlock the drive...
    echo
    sudo cryptsetup luksAddKey /dev/${disk} root.key
    if [ $? != 0 ]
    then
        echo Something went wrong adding the encryption key to /dev/${disk}. Check /etc/crypttab and/or lsblk to determine your encrypted volume, then update this script with the correct value
        exit
    fi
done
```
In my VM's case using the defaults, the code above would see dm_crypt-0 in /etc/crypttab and try to add a key to /dev/dm, which isn't valid and should be /dev/vda3

**Comment by ezaton** [comment]
How come? My line looks like this:
sda3_crypt UUID=4462a1ed-26c7-4bde-ae4a-e54466480c98 none luks,discard,keyscript=/usr/local/sbin/tpm2-getkey,keyscript=/usr/local/sbin/tpm2-getkey

There is no dm_crypt-0, and there should not be. The naming (as presented by Ubuntu. You can manually put whatever you like) is device-name_crypt -> very simple and predictable. Can you share your /etc/crypttab file?

**Comment by kelderek** [comment]
The /etc/crypttab Ubuntu created during the clean install using all defaults was:
```
dm_crypt-0 UUID=b5b7f931-2335-4acf-8600-7ae8712163dd none luks
```
the associated device is /dev/vda3
I didn't manually put in anything, that is the default naming Ubuntu picked for the virtio drives that qemu/kvm used by default.

**Comment by ezaton** [comment]
That is weird, and very unusual. Maybe the script needs to be modified to handle a case where the name is dm_*. It should not be the case, and it is most unusual. Or - it could be replaced by 
`blkid | grep crypto_LUKS | awk '{print $1}'`
which seems to yield the same (correct) result

**Comment by kelderek** [comment]
On my VM that command also grabs a trailing ":" character, but after correcting for that it would work.  In my update, I also wanted the name and device path associated with each other, so I got the device name with 
```
sudo cryptsetup status ${TEMP_DEVICE_NAMES[$I]} | sed -n -E 's/device:\s+(.*)/\1/p'
```
where TEMP_DEVICE_NAMES is an array of all the device names it found in /etc/crypttab.  That works no matter what naming convention is used, even strange manual ones

**Comment by kelderek** [comment]
by "my update" I mean the v0.8.0 branch

**Pull request merged**
